### ISSUE TITLE
Sensor time vs host time

### ISSUE THREAD

**Issue by Huizerd** [ros-event-camera/libcaer_driver#4]
I'm using a setup where I process event packets coming from a DVXplorer in another ROS2 node using `libcaer_driver`, while logging with your [`composable_recorder`](https://github.com/berndpfrommer/rosbag2_composable_recorder). I then read the rosbag with [your reader](https://github.com/ros-event-camera/event_camera_py/blob/master/src/bag_reader_ros2.py), and decode the events with the `event_camera_py` decoder. Eventually, I want to find out the latency of the whole setup, but I started with visualizing the `msg.header.stamp` and `msg.time_base` (which should be host time and sensor time, respectively). By adding the total timespan of the decoded `events["t"]` this gives the time over which a certain packet was recorded (in host and sensor time). See the plot below.

![image](https://github.com/user-attachments/assets/82219bf8-f147-41d5-8019-926ab50a86df)

I noticed that, first of all, sensor time is offset from host time by a couple of seconds. I guess this has to do with the reset of the sensor time after some preset seconds I guess. However, when looking closer at the blue bars for the `msg.header.stamp`, there sometimes is overlap between the timespans of packets (see the middle two lines).

How can this be? Is my adding of `events["t"]` (which is sensor time) to `msg.header.stamp` (which is host time) wrong? I took care to convert the microseconds in `events["t"]` to seconds and nanoseconds for the `.sec` and `.nanosec` fields of `msg.header.stamp`.

My follow up question would be: if I want to determine latency of the whole setup I should do this with respect to a single clock; do you have recommendations on this? I now use `rclpy.clock.Clock().now()` (which is host time as far as I'm concerned) in my listener node, but when plotting this alongside the host time bars from the event packets they now overlap (I check that they refer to the same packet with the `seq` field of the packet):

![image](https://github.com/user-attachments/assets/e943c219-639e-4563-9fce-f17dd3e53ccf)

If `msg.header.stamp` and `rclpy.clock.Clock().now()` were to use the same host time, I would think that green bars should follow shortly after blue bars.

**Comment by berndpfrommer** [comment]
Rarely have I seen such a nicely written issue!

Your first part about the header.stamp being off from the base_time by a couple of seconds is odd. I don't recall seeing this, and this shouldn't be because if you look at the [resetTime()](https://github.com/ros-event-camera/libcaer_driver/blob/1ce6b30245daa05e5866ab4e51dc6e070d7948d4/src/driver.cpp#L158) routine, it captures the ROS time right after calling ``wrapper_->resetTimeStamps()``, which resets the sensor time to zero. At this point ``rosBaseTime_`` should correspond to a sensor time of zero. Later that ``rosBaseTime_`` is used to set [msg.time_base](https://github.com/ros-event-camera/libcaer_driver/blob/1ce6b30245daa05e5866ab4e51dc6e070d7948d4/src/message_converter.cpp#L100). For the first packet received, ``sensorPacketTime`` should be zero, and so ``msg.time_base`` should be identical to ``msg.header.stamp``. If this is not so, then there is a bug or something else going on that I don't understand.

About blue bar overlaps: imagine a sequence of packets being sent by libcaer to the ros driver, produced by libcaer at exactly regular time intervals, and for sake of simplicity, assume each libcaer packet results in a single ROS packet. What happens if at some point the ros driver is busy, and the handling of a libcaer packet is delayed by e.g. 5ms? So the time stamps in your graph for that packet will be shifted to the right. If on the next packet the ROS driver is no longer busy, and handle that packet right away, then you will see the blue bars overlap. On a system with very little other load and low event rate you should see that happening only very rarely. The red bars however should never overlap so long as event time stamps never go backwards (I have seen cases of non-causal time stamps with the prophesee cameras!).

About the green bars vs blue bars of your second graph: it looks like indeed the green bars always start later than the blue bars. What I don't understand is how the width of the green bars could possibly be shorter than that of the blue bars.

I wrote the ROS2 driver mostly with the goal of facilitating recording, not optimal latency,  but nevertheless here some recommendations:
- run the libcaer driver and whatever your processing node is *in the same address space* using composable nodes. The ROS2 middleware can drive you crazy. By running them as composable nodes you cut out the RMW. One less thing to worry about.
-  set the ``event_message_size_threshold`` to zero to force immediate sending of the packet.
-  there are some libcaer knobs that you can play with to get lower latencies, i.e. you can reduce the buffering that libcaer does before it delivers the packet to the ROS driver.  By default this delivery occurs only every 10ms. Reducing that latency is currently not supported by the ROS driver but may not be hard to add. See discussion [here](https://groups.google.com/g/dv-users/c/Pkj7tbhADV8/m/XBIoBVKAAAAJ)

**Comment by Huizerd** [comment]
And rarely have I seen such a complete answer :) Thanks a lot! This gives me enough to go on. If I encounter any bug w.r.t. the time offset I'll reopen this issue.
